Phase 3: add zeroed MASP data for all tokens
anoma/namada-governance-upgrades pull request #20
Opened 2024-11-04 22:02 UTC by brentstone

2024-11-06 16:37 UTC, sug0 requested changes

2024-11-06 16:37 UTC, sug0 commented on phase3/src/lib.rs
> +        .unwrap_or_default();
there's a `read_token_map` function in `shielded_token` you can use instead of this

2024-11-06 16:37 UTC, sug0 commented on phase3/src/lib.rs
> +    ctx.write(&token_map_key, token_map)?;
also a `write_token_map` function

2024-11-06 16:37 UTC, sug0 commented on phase3/src/lib.rs
> +        ctx.write(&shielded_token_kd_gain_key, Dec::zero())?;
`namada_shielded_token::write_params` takes care of all of this

2024-11-06 22:38 UTC, brentstone commented
@tzemanovic we can't implement the suggested changes here from @sug0 because the shielded token crate is not exposed in the `tx_prelude`, should we make those changes to `namada` or just approve this PR as is?

2024-11-07 07:59 UTC, tzemanovic commented
> @tzemanovic we can't implement the suggested changes here from @sug0 because the shielded token crate is not exposed in the `tx_prelude`, should we make those changes to `namada` or just approve this PR as is?

I'd say both - we should expose it but merge this in the meantime

2024-11-08 06:30 UTC, merged